### PR TITLE
Features/14 font awesome

### LINKED ISSUE #14: Add font awesome to be used on channels

### PR DESCRIPTION
**Pull request by Depechie**
Fixes #14

### CODE REVIEW

**Review by rodrigojuarez — COMMENTED** [review]
I will review this one tonight, thanks!

**Review by rodrigojuarez — CHANGES_REQUESTED** [review]
Android version is not compiling, the android renderers are trying to reference FontAwesomeBrandIcon and FontAwesomeIcon

**Comment by rodrigojuarez** [comment]
@Depechie if you push it to a branch in this repo, I can fix the android part

**Comment by Depechie** [comment]
Forgot to commit the removal of those renderers, sorry... done now

**Review by rodrigojuarez — APPROVED** [review]

**Pull request merged**
